[build]
jobs = 1

[profile.dev]
opt-level = 0
debug = 0
debug-assertions = false
overflow-checks = false
panic = "abort"

[profile.release]
opt-level = 1
strip = true
lto = "thin"
panic = "abort"
codegen-units = 1
debug = 0